<div style="height:300px;overflow:auto">
    <table class="select_files">
<?php 
foreach ($this->files as $file) :
?>
        <tr>
            <td><a href="<?=$this->publicPath.'/'.$file?>"><?=file?></a></td>
    <?php 
    if ($this->execFunction) :
    ?>
            <td>
                <a href="javascript:void(0)" onclick="execFunction('<?=$f?>', '<?=$params?>','<?=$component?>');document.getElementById('ajax_loading_bar').style.background='url("<?=BASE_URL?>"images/ajax_loading_bar.gif)';return false;">
            <?=$CustomFunctions->getName($foo)?>
                </a>
            </td>
    <?php 
    endif;
    ?>
        </tr>
<?php 
endforeach;
?>
    </table>
</div>