<select dojoType="dojox.form.CheckedMultiSelect" multiple="true" id="<?php echo $this->domId . $this->i?>" name="<?php echo $this->target?>[]" <?php echo $this->readonly.$this->disabled.$this->required.$this->regexp.$this->trim.$this->invalid_message.$this->prompt_message.$this->onblur.$this->value ?>>
    <?php echo $this->options ?>
</select>
<?php 
if (!empty($this->style)) :
?>
<style type="text/css">
#widget_<?php echo $this->domId . $this->i?> .dojoxCheckedMultiSelectWrapper {
    <?php echo $this->style?>
}
</style>
<?php 
endif;
?>
