<script>
setTimeout(function () {
<?php 
//Si existe atributo formatter se aplica para el select (además de la grilla)
if ($this->formatter) :
?>
    dojo.forEach(dijit.byId('<?php echo $this->domId . $this->i?>').store.data, function(e) {
        e.label = <?php echo $this->formatter?>(e.name)
    });
<?php
    //para saltarse esta parte el nombre la función formatter debe contener el string "formatimage" 
    if (!preg_match("/formatimage/i", $this->formatter)) :
?>
    dijit.byId('<?php echo $this->domId . $this->i?>').textbox.value=<?php echo $this->formatter?>(dijit.byId('<?php echo $this->domId . $this->i?>').get('value'));
    
    dojo.connect(dijit.byId('<?php echo $this->domId . $this->i?>'), 'onchange', function(e){
        dijit.byId('<?php echo $this->domId . $this->i?>').textbox.value=<?php echo $this->formatter?>(dijit.byId('<?php echo $this->domId . $this->i?>').get('value'));
    });
<?php
    endif; 
?>
<?php 
endif;
?>
<?php
if ($this->required) :
?>
    if (dijit.byId('<?php echo $this->domId . $this->i?>').get('value') == '') dijit.byId('<?php echo $this->domId . $this->i?>').set('value', false);
    dojo.connect(dijit.byId('<?php echo $this->domId . $this->i?>'), 'onchange', function(e){
        console.debug('onchange');
        if (dijit.byId('<?php echo $this->domId . $this->i?>').get('value') == '') dijit.byId('<?php echo $this->domId . $this->i?>').set('value', false);
    });
<?php 
endif;
?>
}, 100);
</script>
<select dojoType="dijit.form.FilteringSelect" id="<?php echo $this->domId . $this->i?>" name="<?php echo $this->target?>" onload="dijit.byId('<?php echo $this->domId . $this->i?>').set('value', dijit.byId('<?php echo $this->domId . $this->i?>').get('value'));<?php echo $this->onload ?>" 
    <?php echo $this->readonly.$this->disabled.$this->required.$this->regExp.$this->trim.$this->invalidMessage.$this->onshow.
    $this->promptMessage.$this->onblur.$this->value.$this->onchange.$this->onclick ?> <?php if ($this->formatter) echo ' searchAttr="name" labelAttr="label" labelType="html"'?>>
    <?php echo $this->options ?>
</select>