<script>
setTimeout(function () {
<?php 
//Si existe atributo formatter se aplica para el select (además de la grilla)
if (!$this->data && $this->formatter) :
?>
    dojo.forEach(dijit.byId('<?=$this->domId . $this->i?>').store.data, function(e) {
        e.label = <?=$this->formatter?>(e.name)
    });
<?php
    //para saltarse esta parte el nombre la función formatter debe contener el string "formatimage"
    $labelName = 'label'; 
    if (!preg_match("/formatimage/i", $this->formatter)) :
        $labelName = 'name';
?>
    dijit.byId('<?=$this->domId . $this->i?>').textbox.value=<?=$this->formatter?>(dijit.byId('<?=$this->domId . $this->i?>').get('value'));
<?php
    endif; 
?>
<?php 
endif;
?>
<?php
if ($this->required) :
?>
    if (dijit.byId('<?=$this->domId . $this->i?>').get('value') == '') dijit.byId('<?=$this->domId . $this->i?>').set('value', false);
    dojo.connect(dijit.byId('<?=$this->domId . $this->i?>'), 'onchange', function(e){
        if (dijit.byId('<?=$this->domId . $this->i?>').get('value') == '') dijit.byId('<?=$this->domId . $this->i?>').set('value', false);
    });
<?php 
endif;
?>
}, 100);
</script>
<?php 
$store = '';
if ($this->data) :
    $labelName = 'name';
?>
    <div data-dojo-type="dojo/store/Memory" data-dojo-id="<?=$this->domId . $this->i?>Store" data-dojo-props="data: <?=$this->data?>"></div>
<?php 
    $store = "store:{$this->domId}{$this->i}Store";
endif;
?>
<select data-dojo-type="dijit/form/FilteringSelect" id="<?=$this->domId . $this->i?>" name="<?=$this->target?>" onchange="<?=$this->onchange?>" onload="dijit.byId('<?=$this->domId . $this->i?>').set('value', dijit.byId('<?=$this->domId . $this->i?>').get('value'));<?=$this->onload ?>" data-dojo-props="<?=$store?>" 
    <?=$this->value.$this->readonly.$this->disabled.$this->required.$this->regExp.$this->trim.$this->invalidMessage.$this->onshow.
    $this->promptMessage.$this->onblur.$this->value.$this->onclick ?> <?php if ($this->formatter) echo " searchAttr=\"name\" labelAttr=\"$labelName\" labelType=\"html\""?>>
    <?=$this->options ? $this->options : '' ?>
</select>