<style type="text/css">
    .chartNode {
        width: 800px;
        height:600px;
        background:url(<?=BASE_URL?>css/i/loading.gif) #ffffff;
        background-repeat: no-repeat;
        background-position: center;
    }

    
</style>
<style type="text/css" media="print">
    @media print
    {
    body * { visibility: hidden; }
        #<?=$this->domPrefix;?>printMe * { visibility: visible; }
        #<?=$this->domPrefix;?>printMe { position: absolute; top: 0px; left: -130px; }
    }
</style>
<div id="<?=$this->domPrefix;?>printMe" class="printMe">
    <table>
        <tr>
            <td>
                <div id="<?=$this->domPrefix;?>chartNode" class="chartNode"></div>
            </td>
            <td>  
                <div id="<?=$this->domPrefix;?>chartLegend" class="chartLegend"></div>
            </td>    
        </tr>
    </table>
</div>
<script>
    var base_url = "<?=BASE_URL?>";
    var store;
    var legend;
    var labels = [];
    var useLabelNative = true;
    require([
      "dojox/charting/Chart", 
      "dojox/charting/themes/<?=$this->chartingTheme ?>",
      "dojox/charting/axis2d/Default", 
      "dojox/charting/plot2d/<?=$this->chartType ?>",
      "dojox/charting/action2d/Tooltip",
      "dojox/charting/action2d/Magnify",
      "dojo/data/ItemFileReadStore", 
      "dojox/charting/widget/Legend",
      "dojo/_base/xhr",
      "dojo/domReady!"
    ],
    function(Chart, theme, Default, Lines, Tooltip, Magnify, ItemFileReadStore, Legend, xhr){
        var options = <?=$this->options ?>;
<?php 
if (!empty($this->title)): 
?>
        options.title = '<?=$this->title ?>';
        options.titleFont = "normal normal normal 15pt Verdana";
        options.titleGap = 0;
<?php
endif;
if (!empty($this->model)) :
?>
        var json = xhr.get({
            url:"<?=$this->url ?>", handleAs:"json",
            load: function(resp){
                if (resp.title != undefined) options.title = resp.title;
            
                if (resp.labels != undefined) {
                    useLabelNative = false;
                    i = 0;
                    dojo.forEach(resp.labels, function(label) {
                        labels.push({
                            text: label,
                            value: i
                        });
                        i++;
                    });

                }   
                store = new ItemFileReadStore({
                    data: resp
                });

                store.fetch({
                    onComplete: gotList,
                    onError: gotError
                });
            }
        });


<?php
else :
?>
        store = store_grid;

        store.fetch({
            onComplete: gotList,
            onError: gotError
        });
<?php
endif;
?>
        var gotList = function(items, request){
            console.debug('gotList');
            console.debug(items);
            var chart = new Chart("<?=$this->domPrefix?>chartNode", options);
            chart.setTheme(theme);
            chart.addPlot("default", {
                type: "<?=$this->chartType?>",
                font: "Arial, Verdana",
                animate: {duration: 1800}    
            });

     
            var item = {};
            var itemsList = [];
            var x = 0;

            chart.addAxis("x", {vertical: true, fixLower: "major", fixUpper: "major" });

            dojo.forEach(items, function(i) {
                if (useLabelNative) { labels.push(store.getLabel(i)); }  
                itemsList = [];
                item = store.getValue(i, "<?=$this->items ?>");
                x = 0;
                dojo.forEach(store.getValues(i, "<?=$this->yTarget ?>"), function(value) {
                    itemsList.push({x: x, y: value, tooltip:"<b>" + item + "</b><br/>"+labels[x].text+"<br/>" + value});
                    x++;
                }); 
                chart.addSeries(item, itemsList);

            });

            chart.addAxis("y", {'labels': labels, rotation: 90});
            
            var tip = new Tooltip(chart, "default");
            
            // Create the magnifier
            var mag = new Magnify(chart, "default");
            
            // Render the chart!
            chart.render();
            
            // Create the legend
            legend = new dojox.charting.widget.Legend({ chart: chart, horizontal: false }, "<?=$this->domPrefix;?>chartLegend");
        };
        
        var gotError = function(error, request){
            console.debug(request);
            console.debug(error);
            //alert("¡Vaya! ha ocurrido un error: " +  error);
        };

    });
</script>
<button type="button" class="dijitIconPrint" style="width:21px;position:absolute;top:24px;left:16px;" iconClass="dijitIconPrint" id="btnPrint" title="Imprimir" onClick="window.print();"></button>