<div>
        <div>
            <input type="text" id="<?=$this->domId.$this->i?>" data-dojo-type="dijit/form/ValidationTextBox" <?=$this->promptMessage . $this->invalidMessage?>
            data-dojo-props="
            value: '<?=$this->value?>',
            required: true,
            onKeyUp: function() {
                dijit.byId('<?=$this->domId.$this->i?>Slider').set('value', this.get('value'));
            },
            validator: function() {
                return this.get('value') >= <?=$this->minimum?> && this.get('value') <= <?=$this->maximum?>;
            }
            " />
        </div>
        <div style="margin-top: 0.2em; margin-bottom: 0.2em;">
            <div id="<?=$this->domId.$this->i?>Slider"
                style="width:100%;"
                name="<?=$this->target?>"
                data-dojo-type="dijit/form/HorizontalSlider"
                data-dojo-props="
                value: <?=$this->value?>,
                minimum: <?=$this->minimum?>,
                maximum: <?=$this->maximum?>,
                discreteValues: <?=$this->discreteValues?>,
                intermediateChanges:true,
                onChange: function(value) {
                    dijit.byId('<?=$this->domId.$this->i?>').set('value', value);
                },
                showButtons:false">
            </div>
         </div>
</div>