<script>
setTimeout(function () {
<?php
if ($this->data && $this->value && $this->mode == 'add') :
?>
    dijit.byId('<?=$this->domId . $this->i?>').set('value', '<?=$this->value?>');
<?php
endif;
?>
<?php
if ($this->required) :
?>
    if (dijit.byId('<?=$this->domId . $this->i?>').get('value') == '') dijit.byId('<?=$this->domId . $this->i?>').set('value', false);
    dojo.connect(dijit.byId('<?=$this->domId . $this->i?>'), 'onchange', function(e){
        if (dijit.byId('<?=$this->domId . $this->i?>').get('value') == '') dijit.byId('<?=$this->domId . $this->i?>').set('value', false);
    });
<?php 
endif;
?>
}, 100);
</script>
<?php 
$store = '';
$value = '';
if ($this->data) :
    $labelName = 'name';
    $value = " value=\"$this->value\"";
?>
    <div data-dojo-type="dojo/store/Memory" data-dojo-id="<?=$this->domId . $this->i?>Store" data-dojo-props="data: <?=$this->data?>"></div>
<?php 
    $store = "store:{$this->domId}{$this->i}Store";
endif;
?>
<select data-dojo-type="dijit/form/Select" id="<?=$this->domId.$this->i?>" name="<?=$this->target?>" onchange="<?=$this->onchange?>" onload="dijit.byId('<?=$this->domId . $this->i?>').set('value', dijit.byId('<?=$this->domId . $this->i?>').get('value'));<?=$this->onload ?>" data-dojo-props="<?=$store?>" 
    <?=$value.$this->readonly.$this->disabled.$this->required.$this->invalidMessage.$this->onshow.
    $this->promptMessage.$this->placeHolder.$this->onblur.$this->onclick.$this->trim ?> <?php if ($this->formatter) echo " searchAttr=\"name\" labelAttr=\"$labelName\" labelType=\"html\""?> style="width: 15em">
    <?=$this->options ? $this->options : '' ?>
</select>