<div class="keyPadWrapper">
<?php
if ($this->add) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconNewTask" id="<?php echo $this->domPrefix?>btnAdd" onClick="
                    var form = new zwei.Form({
                        component: '<?php echo $this->component?>',
                        ajax: <?php echo $this->ajax ?>,
                        action: 'add',
                        dijitDialog: dijit.byId('<?php echo $this->domPrefix?>dialog_add'), 
                        dijitForm: dijit.byId('<?php echo $this->domPrefix?>form_add'), 
                        dijitDataGrid: dijit.byId('<?php echo $this->domPrefix?>dataGrid')
                    }); 
                    form.showDialog()">
        Agregar <?php echo $this->name ?>
        </button>
    </div>
<?php 
endif;
?>
     
<?php 
if ($this->edit) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconEdit" id="<?php echo $this->domPrefix?>btnEdit" onClick="
                var form = new zwei.Form({
                    ajax: <?php echo $this->ajax ?>,
                    component: '<?php echo $this->component?>',
                    action: 'edit',
                    dijitDialog: dijit.byId('<?php echo $this->domPrefix?>dialog_edit'), 
                    dijitForm: dijit.byId('<?php echo $this->domPrefix?>form_edit'), 
                    dijitDataGrid: dijit.byId('<?php echo $this->domPrefix?>dataGrid')
                }); 
                form.showDialog()">
            Editar <?php echo $this->name ?>
        </button>
    </div>
<?php 
endif;
?>
<?php 
if ($this->delete) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconDelete" id="<?php echo $this->domPrefix?>btnDelete" onClick="
                var form = new zwei.Form({
                    ajax: <?php echo $this->ajax ?>,
                    action: 'delete',
                    component: '<?php echo $this->component?>',
                    dijitDialog: dijit.byId('<?php echo $this->domPrefix?>dialog_edit'), 
                    dijitForm: dijit.byId('<?php echo $this->domPrefix?>form_edit'), 
                    dijitDataGrid: dijit.byId('<?php echo $this->domPrefix?>dataGrid'),
                    dijitFormSearch: dijit.byId('<?php echo $this->domPrefix?>formSearch')
                }); 
                form['delete']()">
            Eliminar <?php echo $this->name ?>
        </button>
    </div>
<?php 
endif;
?>
<?php
if ($this->clone) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconNewTask" id="<?php echo $this->domPrefix?>btnClone" onClick="
                var form = new zwei.Form({
                    ajax: <?php echo $this->ajax ?>,
                    component: '<?php echo $this->component?>',
                    action: 'clone',
                    dijitDialog: dijit.byId('<?php echo $this->domPrefix?>dialog_add'), 
                    dijitForm: dijit.byId('<?php echo $this->domPrefix?>form_add'), 
                    dijitDataGrid: dijit.byId('<?php echo $this->domPrefix?>dataGrid')
                }); 
                form.showDialog()">
                Clonar <?php echo $this->name ?>
        </button>
    </div>
<?php 
endif;
?>

<?php 
if ($this->changePassword) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconEdit" id="<?php echo $this->domPrefix?>btnChangePassword" onClick="
            var form = new zwei.Form({
                ajax: <?php echo $this->ajax ?>,
                component: '<?php echo $this->component?>',
                action: 'edit',
                dijitDialog: dijit.byId('<?php echo $this->domPrefix?>dialog_editpass'), 
                dijitForm: dijit.byId('<?php echo $this->domPrefix?>form_editpass'), 
                dijitDataGrid: dijit.byId('<?php echo $this->domPrefix?>dataGrid')
            }); 
            form.showDialog()">
            Cambiar Contrase&ntilde;a
        </button>
    </div>
<?php 
endif;
?>
</div>
