<div class="dndWrapper" title="Arrastre y suelte los items para seleccionar o deseleccionar.\n Click ">
    <div class="dndContainer">
        <div style="margin: 0 auto; text-align: center ">
                <h5 onclick="
                    var searcher = dijit.byId('search<?=$this->domId. $this->i?>inStockSearch');
                    var isHidden = searcher.get('style').display == undefined || searcher.get('style').display == 'none';
                    
                    searcher.set('style', {display:  (isHidden ? 'inline-block' : 'none')});
                    if (isHidden) searcher.focus();
                    " 
                    style="cursor: pointer" title="Click para buscar."><?=$this->selectedTitle?></h5>
                <input id="search<?=$this->domId. $this->i?>inStockSearch" type="text" data-dojo-type="dijit/form/ValidationTextBox" style="display:none" data-dojo-props="
                intermediateChanges: true,
                onKeyDown: function (event) {
                    if (event.keyCode == dojo.keys.ENTER) {
                        dojo.stopEvent(event);
                    }
                },
                onChange: function(p) {
                    var value = this.get('value');
                    dojo.query('#inStock<?=$this->domId. $this->i?> .dojoDndItem').forEach(function(node) {
                       node.style.display = (value == '') ? 'list-item' : 'none';
                       var innerText = node.innerText || node.textContent;
                       if (self.value != '' && innerText.toLowerCase().indexOf(value.toLowerCase()) > 0) {
                           node.style.display='list-item';
                       }
                    });
                }" />
        </div>
        <ul data-dojo-type="dojo.dnd.Source" data-dojo-props="accept: [ 'inStock', 'outStock' ]" id="inStock<?=$this->domId. $this->i?>" class="dndList inStock" >
        <script type="dojo/connect" event="onDropExternal" args="source, nodes, copy">
            var node;
            for (var i = 0; i < nodes.length; i++) {
                node = nodes[i];
                for (var j = 0; j < node.childNodes.length; j ++) {
                    if (node.childNodes[j].nodeName == 'INPUT') {
                        node.childNodes[j].disabled = false;
                        break;
                    }
                }
            }
        </script>
<?php 
foreach ($this->selectedItems as $i => $v) :
?>
            <li class="dojoDndItem" dndType="inStock" title="<?=$v?>"><input type="hidden" id="outStock<?=$this->domId . $this->i?>" name="<?=$this->target?>[]" value="<?=$i?>"/>
            <?=$v?>
            </li>
<?php 
endforeach;
?>
        </ul>
    </div>
    <div class="dndContainer">
        <div style="margin: 0 auto; text-align: center ">
            <h5 onclick="
                        var searcher = dijit.byId('search<?=$this->domId. $this->i?>outStockSearch');
                        var isHidden = searcher.get('style').display == undefined || searcher.get('style').display == 'none';
                        
                        searcher.set('style', {display:  (isHidden ? 'inline-block' : 'none')});
                        if (isHidden) searcher.focus();
                        " 
                        style="cursor: pointer" title="Click para buscar."><?=$this->unselectedTitle?></h5>
            <input id="search<?=$this->domId. $this->i?>outStockSearch" type="text" data-dojo-type="dijit/form/ValidationTextBox" style="display:none" data-dojo-props="
                    intermediateChanges: true,
                    onKeyDown: function (event) {
                        if (event.keyCode == dojo.keys.ENTER) {
                            dojo.stopEvent(event);
                        }
                    },
                    onChange: function(p) {
                        var value = this.get('value');
                        console.debug(value);
                        dojo.query('#outStock<?=$this->domId. $this->i?> .dojoDndItem').forEach(function(node) {
                            node.style.display = (value == '') ? 'list-item' : 'none';
                            var innerText = node.innerText || node.textContent;
                            if (self.value != '' && innerText.toLowerCase().indexOf(value.toLowerCase()) > 0) {
                               node.style.display='list-item';
                            }
                        });
                    }" />
        </div>
        <ul data-dojo-type="dojo.dnd.Source" data-dojo-props="accept: [ 'inStock', 'outStock' ]" id="outStock<?=$this->domId. $this->i?>" class="dndList outStock">
            <script type="dojo/connect" event="onDropExternal" args="source, nodes, copy">
            var node;
            for (var i = 0; i < nodes.length; i++) {
                node = nodes[i];
                for (var j = 0; j < node.childNodes.length; j ++) {
                    if (node.childNodes[j].nodeName == 'INPUT') {
                        node.childNodes[j].disabled = true;
                        break;
                    }
                }
            }
            </script>
<?php 
foreach ($this->unselectedItems as $i => $v) :
?>
            <li class="dojoDndItem" dndType="outStock" title="<?=$v?>"><input type="hidden" id="<?=$this->domId . $this->i?>" name="<?=$this->target?>[]" value="<?=$i?>" disabled="disabled"/>
            <?=$v?>
            </li>
<?php 
endforeach;
?>
        </ul>
    </div>
</div>