<script type="text/javascript" src="<?=BASE_URL?>/js/md5.js"></script>
<form data-dojo-type="dijit/form/Form" target="ifrm_process" id="<?=$this->domPrefix?>form_editpass" class="tabForm" jsId="<?=$this->domPrefix?>form_editpass" name="<?=$this->domPrefix?>form_editpass" encType="multipart/form-data"  action="<?=BASE_URL?>crud-request" method="post">
    <div class="brclear"></div>
    <table>
        <tr>
            <th><label for="<?=$this->targetPass?>">Contrase&ntilde;a</label></th>
            <td><?=$this->action('index', 'dijit-form-validation-text-box', 'elements', $this->inputParams)?></td>
        </tr>
        <tr>
            <th><label for="<?=$this->targetPass?>confirm">Repetir</label></th>
            <td><?=$this->action('index', 'dijit-form-validation-text-box', 'elements',  $this->inputConfirmParams)?></td>
        </tr>
    </table>
    <input type="hidden" name="format" value="json" />
    <input type="hidden" name="action" value="edit" />
    <input type="hidden" name="model" value="<?=$this->model?>" />
    <input type="hidden" name="p" value="<?=$this->p?>" />
<?php 
foreach ($this->modelPrimary as $p) :
    $value = isset($_REQUEST['primary']) ? $_REQUEST['primary'][$p] : '';
?>
    <input type="hidden" name="primary[<?=$p?>]" value="<?=$value?>" />
<?php 
endforeach;
?>
    <script type="dojo/method" event="onSubmit">
    if (this.validate()) {
        var domForm = dojo.byId(this.id);
        if (domForm['data[<?=$this->targetPass?>]'].value != domForm['confirm[<?=$this->targetPass?>]'].value) {
            utils.showMessage('Las contraseñas no coinciden.', 'error');
            return false;
        } else {
            var decodedValue = domForm['data[<?=$this->targetPass?>]'].value;
            domForm['data[<?=$this->targetPass?>]'].value = hex_md5(decodedValue);
            console.debug(domForm);
        }
        try {
            var form = new zwei.Form({
                dijitForm: this, 
                dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_editpass'),
                dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid'),
                dijitFormSearch: dijit.byId('<?=$this->domPrefix?>formSearch'),
                iframe: dojo.byId('ifrm_process')
            });
            <?=$this->onSubmit?>
            var observer = form.watch("response", function(name, oldValue, response) {
                if (response != null) {
                    <?=$this->onPostSubmit?>
                    if (response.todo == 'goToLogin') window.location.href = base_url + '/login';
                    else if (response.todo == 'cargarArbolMenu') admportal.loadMainMenu();
                    this.set("response", null);
                    domForm['data[<?=$this->targetPass?>]'].value = '';
                    domForm['confirm[<?=$this->targetPass?>]'].value = '';
                }
            });
            form.save();
            
        } catch (e) {
            console.debug(e);
            utils.showMessage(e.message, 'error');
        }
        return false;
    } else {
        utils.showMessage('Por favor corrija los campos marcados.', 'error');
        return false;
    }
    return true;
    </script>
    <button data-dojo-type="dijit/form/Button" id="<?=$this->domPrefix?>tabs_btn_saveeditpass" type="submit" >Guardar</button>
</form>