<script>
dojo.require("dojox.grid.enhanced.plugins.Menu");
dojo.require("dijit.Menu");
dojo.require("dijit.MenuItem");
dojo.require('dijit.MenuSeparator');
dojo.require('dijit.PopupMenuItem');

var menu<?=$this->domPrefix?> = new dijit.Menu({});
<?php
if ($this->add) :
?>
menu<?=$this->domPrefix?>.addChild(new dijit.MenuItem({
    label: "Agregar <?=$this->name ?>",
    iconClass: "dijitIconNewTask",
    onClick : function(e){
        var form = new zwei.Form({
            component: '<?=$this->component?>',
            ajax: <?=$this->ajax ?>,
            action: 'add',
            dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_add'), 
            dijitForm: dijit.byId('<?=$this->domPrefix?>form_add'), 
            dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid'),
            queryParams: '<?=$this->queryParams?>'
        }); 
        form.showDialog()
    }
}));
<?php
endif;
?>
<?php
if ($this->edit) :
?>
menu<?=$this->domPrefix?>.addChild(new dijit.MenuItem({
    label: "Editar <?=$this->name ?>",
    iconClass: "dijitIconEdit",
    onClick : function(e){
        var form = new zwei.Form({
            ajax: <?=$this->ajax ?>,
            component: '<?=$this->component?>',
            action: 'edit',
            dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_edit'), 
            dijitForm: dijit.byId('<?=$this->domPrefix?>form_edit'), 
            dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')
        }); 
        form.showDialog() 
    }
}));
<?php
endif;
?>
<?php 
if ($this->delete) :
?>
menu<?=$this->domPrefix?>.addChild(new dijit.MenuItem({
    label: "Eliminar <?=$this->name ?>",
    iconClass: "dijitIconDelete",
    onClick : function(){
        var form = new zwei.Form({
            ajax: <?=$this->ajax ?>,
            action: 'delete',
            component: '<?=$this->component?>',
            dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_edit'), 
            dijitForm: dijit.byId('<?=$this->domPrefix?>form_edit'), 
            dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid'),
            dijitFormSearch: dijit.byId('<?=$this->domPrefix?>formSearch')
        }); 
        form['delete']();
    }
}));
<?php
endif;
?>
<?php 
if ($this->clone) :
?>
menu<?=$this->domPrefix?>.addChild(new dijit.MenuItem({
    label: "Clonar <?=$this->name ?>",
    iconClass: "dijitIconNewTask",
    onClick : function(){
        var form = new zwei.Form({
            ajax: <?=$this->ajax ?>,
            component: '<?=$this->component?>',
            action: 'clone',
            dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_add'), 
            dijitForm: dijit.byId('<?=$this->domPrefix?>form_add'), 
            dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')
        }); 
        form.showDialog();
    }
}));
<?php
endif;
?>
<?php 
if ($this->changePassword) :
?>
menu<?=$this->domPrefix?>.addChild(new dijit.MenuItem({
    label: "Cambiar Contraseña",
    iconClass: "dijitIconEdit",
    onClick : function(){
        var form = new zwei.Form({
            ajax: <?=$this->ajax ?>,
            component: '<?=$this->component?>',
            action: 'edit',
            dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_editpass'), 
            dijitForm: dijit.byId('<?=$this->domPrefix?>form_editpass'), 
            dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')
        }); 
        form.showDialog();
    }
}));
<?php
endif;
?>
<?php 
foreach ($this->customFunctions as $i => $f) :
?>
menu<?=$this->domPrefix?>.addChild(new dijit.MenuItem({
    label: "<?=$f['name'] ? $f['name'] : $f['target']?>",
    iconClass: "<?=$f['iconClass'] ? $f['iconClass'] : 'dijitIconFunction'?>",
    onClick : function(){
        admportal.execFunction('<?=$f['target']?>', '', '<?=$this->component?>', '<?=$this->primary?>', '<?=$this->domPrefix?>');
    }
}));
<?php 
endforeach;
?>
<?php 
foreach ($this->excel as $i => $f) :
    $formatter = $f->getAttribute('formatter') ? $f->getAttribute('formatter') : $this->zweiExcelVersion;
    $name = $f->getAttribute('name') ? $f->getAttribute('name') : 'Descargar como Excel' ;
?>
menu<?=$this->domPrefix?>.addChild(new dijit.MenuItem({
    label: "<?=$name?>",
    iconClass: "dijitLeaf",
    onClick : function(){
        var form = new zwei.Form({
            dijitFormSearch: dijit.byId('<?=$this->domPrefix ?>formSearch'), 
            dijitDataGrid: dijit.byId('<?=$this->domPrefix ?>dataGrid'), 
            queryParams: 'format=excel&excel_formatter=<?=$formatter?>',
            iframe: dojo.byId('ifrm_process')
        });
        form.loadData();
    }
}));
<?php 
endforeach;
?>
menu<?=$this->domPrefix?>.startup();
</script>
