<?=$this->includeJs?>
<?php 
$modAux = $this->mode != 'clone' ? $this->mode : 'add';
?>
<script type="text/javascript">
    globalOpc = '<?=$this->mode ?>';
</script>
<form data-dojo-type="dijit/form/Form" target="ifrm_process" id="<?=$this->domPrefix?>form_<?=$modAux?><?=$this->dialogIndex?>" domsufix="<?=$this->dialogIndex?>" class="tabForm" jsId="<?=$this->domPrefix?>form_<?=$modAux?><?=$this->dialogIndex?>" name="<?=$this->domPrefix?>form_<?=$modAux?>" encType="multipart/form-data"  action="<?=BASE_URL?>crud-request" method="post">
<?php 
if ($this->onShow) :
?>
    <script type="dojo/on" data-dojo-event="show">
        <?=$this->onShow?>
    </script>
<?php 
endif;
?>
<?php 
$i = 0;
$tableWrapperClass = '';

if (!$this->loadPartial) :
    if (count($this->tabs) > 1) :
        $tableWrapperClass = "settingsArea";
        foreach ($this->tabs as $tab) :
            //if ($tab->getAttribute($this->mode) !== 'false') :
            $style = $tab->getAttribute('style');
            $activeClass =  $i == 0 ? "active" : "";
            $i++;
?>
    <a id="<?=$this->domPrefix .'tab_'. $modAux .'_ctrl'. $i?><?=$this->dialogIndex?>" class="settingsTab <?=$activeClass?>" <?=$style ?> onclick="admportal.switchTabs('<?=$this->domPrefix?>form_<?=$modAux?><?=$this->dialogIndex?>', this.id, '<?=$this->domPrefix.'tab_'.$modAux.$i?><?=$this->dialogIndex?>');<?=$tab->getAttribute('onClick')?>"><?=$tab->getAttribute('name') ?></a>
<?php 
            //endif;
        endforeach;
    endif;
?>
    <div class="brclear"></div>
<?php
    $i=0;
    $j=0;
    foreach ($this->tabs as $tab) :
        $style = $i == 0 ? 'style="display:block"' : 'style="display:none"'; 
        $dataDojoType = is_object($tab) && $tab->getAttribute('dojoType') ? "data-dojo-type=\"{$tab->getAttribute('dojoType')}\"" : "";
        $i++;
?>
    <div id="<?=$this->domPrefix.'tab_'.$modAux.$i?><?=$this->dialogIndex?>" class="settingsArea" <?=$style ?> <?=$dataDojoType?> data-dojo-props="executeScripts: true">
        <table>
<?php 
        $k=0;
        foreach ($tab as $element) :
            $j++;
            $k++;
            $hidden = '';
            $params = (array) $element->attributes();
            $params = $params['@attributes'];
            
            if (isset($params[$this->mode]) && $params[$this->mode] !== 'false') :
                if ($element->existsChildren('tinyMceInit')) {
                    $params['tinyMceInit'] = dom_import_simplexml($element->tinyMceInit)->textContent;
                }
                
                if ($element->existsChildren('thumb')) {
                    $params['thumbs'] = array();
                    foreach ($this->xml->xpath("//elements/element[@target='{$params['target']}']/thumb") as $t) {
                        $params['thumbs'][] = $t;
                    }
                }
                
                $params['domId'] = $this->domPrefix . "_{$modAux}_".$this->dialogIndex;
                $params['mode'] = $this->mode;
                $params['i'] = $j;
                if (!isset($params['type'])) {
                    throw new Zwei_Exception("Nodo XML <element> debe tener atributo 'type'.");
                }
                
                $hidden = $params['type'] == 'hidden' ? ' style="display:none"' : '';
                
                if (isset($_REQUEST[$params['target']])) $params['value'] = $_REQUEST[$params['target']]; //Esto aplica para formularios cargados vía ajax
                if (isset($this->data[$params['target']])) $params['value'] = $this->data[$params['target']];
                
                $params['target'] = "data[{$params['target']}]";
?>
            <tr<?=$hidden?>>
                <th><label for="<?=$element->getAttribute('target')?>"><?=$element->getAttribute('name') ?></label></th>
                <td><?=$this->action('index', $element->getAttribute('type'), 'elements', $params); ?></td>
            </tr>
<?php 
            endif;
        endforeach;
?>
        </table>
    </div>
<?php
    endforeach;
endif;
?>
    <input type="hidden" name="format" value="json" />
    <input type="hidden" name="action" value="<?=$modAux?>" />
    <input type="hidden" name="model" value="<?=$this->model?>" />
    <input type="hidden" name="p" value="<?=$this->p?>" />
<?php 
//if ($this->mode == 'edit' || $this->mode == 'clone') :
    foreach ($this->modelPrimary as $p) :
        $value = isset($_REQUEST['primary']) ? $_REQUEST['primary'][$p] : '';
?>
    <input type="hidden" name="primary[<?=$p?>]" value="<?=$value ?>" />
<?php 
    endforeach;
//endif;
?>
    <script type="dojo/method" event="onSubmit">
    if (this.validate()) {
        try {
            var form = new zwei.Form({
                dijitForm: this, 
                dijitDialog: dijit.byId('<?=$this->dijitDialogId?>'),
                dijitDataGrid: dijit.byId('<?=$this->dijitDataGridId?>'),
                dijitFormSearch: dijit.byId('<?=$this->dijitFormSearchId?>'),
                iframe: dojo.byId('ifrm_process')
            });
            <?=$this->onSubmit ?>
            admportal.lockScreen();
            var name, oldValue, response;
            var observer = form.watch("response", function(name, oldValue, response) {
                if (response != null) {
                    <?=$this->onPostSubmit ?>
                    if (response.todo == 'goToLogin') window.location.href = base_url + 'admin/login';
                    else if (response.todo == 'cargarArbolMenu') admportal.loadMainMenu();
                    this.set("response", null);
                    admportal.lockScreen(false);
                }
                console.log('observer');
            });

            form.save();
            
        } catch (e) {
            admportal.lockScreen(false);
            utils.showMessage(e.message, 'error');
        }
        return false;
    } else {
        utils.showMessage('Por favor corrija los campos marcados.', 'error');
        return false;
    }
    return true;
    </script>
    <button data-dojo-type="dijit/form/Button" id="<?=$this->domPrefix?>tabs_btn_save<?=$modAux?><?=$this->dialogIndex?>" type="submit" iconClass="dijitIconSave">Guardar</button>
</form>
