<div class="keyPadWrapper">
<?php
if ($this->add) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconNewTask" id="<?=$this->domPrefix?>btnAdd" onClick="
                    var form = new zwei.Form({
                        component: '<?=$this->component?>',
                        ajax: <?=$this->ajax ?>,
                        action: 'add',
                        dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_add'), 
                        dijitForm: dijit.byId('<?=$this->domPrefix?>form_add'), 
                        dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')
                    }); 
                    form.showDialog()">
        Agregar <?=$this->name ?>
        </button>
    </div>
<?php 
endif;
?>
     
<?php 
if ($this->edit) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconEdit" id="<?=$this->domPrefix?>btnEdit" onClick="
                var form = new zwei.Form({
                    ajax: <?=$this->ajax ?>,
                    component: '<?=$this->component?>',
                    action: 'edit',
                    dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_edit'), 
                    dijitForm: dijit.byId('<?=$this->domPrefix?>form_edit'), 
                    dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')
                }); 
                form.showDialog()">
            Editar <?=$this->name ?>
        </button>
    </div>
<?php 
endif;
?>
<?php 
if ($this->delete) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconDelete" id="<?=$this->domPrefix?>btnDelete" onClick="
                var form = new zwei.Form({
                    ajax: <?=$this->ajax ?>,
                    action: 'delete',
                    component: '<?=$this->component?>',
                    dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_edit'), 
                    dijitForm: dijit.byId('<?=$this->domPrefix?>form_edit'), 
                    dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid'),
                    dijitFormSearch: dijit.byId('<?=$this->domPrefix?>formSearch')
                }); 
                form['delete']()">
            Eliminar <?=$this->name ?>
        </button>
    </div>
<?php 
endif;
?>
<?php
if ($this->clone) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconNewTask" id="<?=$this->domPrefix?>btnClone" onClick="
                var form = new zwei.Form({
                    ajax: <?=$this->ajax ?>,
                    component: '<?=$this->component?>',
                    action: 'clone',
                    dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_add'), 
                    dijitForm: dijit.byId('<?=$this->domPrefix?>form_add'), 
                    dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')
                }); 
                form.showDialog()">
                Clonar <?=$this->name ?>
        </button>
    </div>
<?php 
endif;
?>

<?php 
if ($this->changePassword) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="dijitIconEdit" id="<?=$this->domPrefix?>btnChangePassword" onClick="
            var form = new zwei.Form({
                ajax: <?=$this->ajax ?>,
                component: '<?=$this->component?>',
                action: 'edit',
                dijitDialog: dijit.byId('<?=$this->domPrefix?>dialog_editpass'), 
                dijitForm: dijit.byId('<?=$this->domPrefix?>form_editpass'), 
                dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')
            }); 
            form.showDialog()">
            Cambiar Contrase&ntilde;a
        </button>
    </div>
<?php 
endif;
?>
<?php 
foreach ($this->customFunctions as $i => $f) :
?>
    <div class="keyPadButton">
        <button type="button" dojoType="dijit.form.Button" iconClass="<?=$f['iconClass'] ? $f['icon'] : 'dijitIconFunction'?>" id="<?=$this->domPrefix?>btnFunction<?=$i?>" onClick="
            admportal.execFunction('<?=$f['target']?>', '', '<?=$this->component?>', '<?=$this->primary?>', '<?=$this->domPrefix?>');">
        <?=$f['name'] ? $f['name'] : $f['target']?>
        </button>
    </div>
<?php 
endforeach;
?>
</div>
