<?php 
if (count($this->groups) > 0) :
?>
<div data-dojo-type="dijit/form/Form" class="formSearch" id="<?=$this->domPrefix?>formSearch" jsId="<?=$this->domPrefix?>formSearch" encType="multipart/form-data" action="" method="">
    <div class="formSearchInputs">
<?php 
    $i = 0;
    foreach ($this->groups as $group) :
        $params = (array) $group->attributes();
        $params = $params['@attributes'];
        $params['domId'] =  $this->domPrefix . '_search_';
        $params['i'] = $i;
?>
        <div class="formSearchItemContainer">
            <div class="item">
                <label for="search" class="formSearchItemLabel"><?=$group->getAttribute('name')?></label>
                <?=$this->action('index', $group->getAttribute('type'), 'elements', $params);?>
                <input type="hidden" value="<?=$group->getAttribute('format')?>" id="<?=$this->domPrefix . '_search_' . $i?>_format" name="<?=$group->getAttribute('target')?>_format" />
                <input type="hidden" value="<?=$group->getAttribute('operator')?>" id="<?=$this->domPrefix . '_search_' . $i?>_operator" name="<?=$group->getAttribute('target')?>_operator" />
<?php 
    if ($group->getAttribute('sufix')) :
?>
                <input type="hidden" value="<?=$group->getAttribute('sufix')?>" id="<?=$this->domPrefix . '_search_' . $i?>_sufix" name="<?=$group->getAttribute('target')?>_sufix" />
<?php 

    endif;
    if ($group->getAttribute('prefix')) :
?>
                <input type="hidden" value="<?=$group->getAttribute('prefix')?>" id="<?=$this->domPrefix . '_search_' . $i?>_prefix" name="<?=$group->getAttribute('target')?>_prefix" />
<?php 
    endif;
?>
            </div>
<?php 
       $k = 0;
       if (count($group->children()) > 1) :
           
           if ($group->getAttribute('operator') != 'between') :
?>
           <div class="formSearchSelectors">
<?php
           
               foreach ($group->children() as $element) :
                   if ($element->getAttribute('name')) {
                      $eName = $element->getAttribute('name');
                   } else {
                      $targets = $this->xml->getElements("@target='{$element->getAttribute('target')}'");
                      $eName = $targets[0]->getAttribute('name');
                   }
?>
                <div class="formSearchSelectorItem">
                    <input data-dojo-type="dijit/form/RadioButton" id="<?=$this->domPrefix?>searchFields[<?=$i?>][<?=$k?>]" name="switchFields[<?=$i?>]" <?php if ($k == 0) echo 'checked="checked"' ?> value="<?=$element->getAttribute('target') ?>" type="radio" onClick="dijit.byId('<?=$this->domPrefix . '_search_' . $i?>').set('name', this.value)" />
                    <label for="<?=$element->getAttribute('target')?>"><?=$eName?></label>
                </div>
<?php 
                $k++;
                endforeach;
?>
            </div>
<?php
            else :
                $j=0;
                foreach ($group->children() as $element) :
                    $j++;
                    if ($j >= 2) :
?>
            <input type="hidden" id="<?=$this->domPrefix . '_search_' . $i?>_sufix<?=$j?>" value="<?=$element->getAttribute('sufix')?>" name="<?=$group->getAttribute('target')?>_sufix" />
            <input type="hidden" id="<?=$this->domPrefix . '_search_' . $i?>_prefix<?=$j?>" value="<?=$element->getAttribute('prefix')?>" name="<?=$group->getAttribute('target')?>_prefix" />
<?php 
                    endif;
                endforeach;
            endif;
        endif;
?>
        </div>
<?php 
        $i++;
    endforeach;
?>
    </div>
    <div class="formSearchSubmit">
        <input type="hidden" name="model" value="<?=$this->model ?>" />
        <input type="hidden" name="format" value="json" />
        <input type="hidden" name="storeType" value="query" />
        <button type="submit" class="submit" data-dojo-type="dijit/form/Button" iconClass="dijitIconSearch" id="<?=$this->domPrefix?>btnBuscar">Buscar</button>
    </div>

    <script type="dojo/method" event="onSubmit">
        if (this.validate()) {
            try {
                var form = new zwei.Form({dijitFormSearch: this, dijitDataGrid: dijit.byId('<?=$this->domPrefix?>dataGrid')});
                form.loadData();
            } catch(e) {
                alert(e.message)
            }
            return false;
        } else {
            alert('Por favor corrija los campos marcados.');
            return false;
        }
        return true;
    </script>
</div>
<?php 
endif;
?>
