<?php 
if (count($this->groups) > 0) {
?>
<div dojoType="dijit.form.Form" class="formSearch" id="<?php echo $this->domPrefix?>formSearch" jsId="<?php echo $this->domPrefix?>formSearch" encType="multipart/form-data" action="" method="">
    <div class="formSearchInputs">
<?php 
    foreach ($this->groups as $i => $group) :
        $gName = $group->getAttribute('name') 
            ? $group->getAttribute('name') 
            : (isset($this->xml->getElements("@target='{$group->getAttribute('target')}'")[0]) ?
                $this->xml->getElements("@target='{$group->getAttribute('target')}'")[0]->getAttribute('name') : ''
              );
        
        $gType = $group->getAttribute('type') 
            ? $group->getAttribute('type') 
            : (isset($this->xml->getElements("@target='{$group->getAttribute('target')}'")[0]) ?
                $this->xml->getElements("@target='{$group->getAttribute('target')}'")[0]->getAttribute('type') : 'Zwei_Admin_Elements_DojoValidationTextbox'
              );
        //$input = new $gType();
?>
        <div class="formSearchItemContainer">
            <div class="item">
                <label for="search" class="formSearchItemLabel"><?php echo $gName ?></label>
                <input type="text" name="search" placeHolder="Ingresar" dojoType="dijit.form.ValidationTextBox" trim="true" id="<?php echo $this->domPrefix?>search<?php echo $i ?>"/>
            </div>
<?php 
       $k = 0;
       if (count($group->children()) > 1) :
?>
           <div class="formSearchSelectors">
<?php
           foreach ($group->children() as $j => $element) :
               $eName = $element->getAttribute('name')
               ? $element->getAttribute('name')
               : $this->xml->getElements("@target='{$element->getAttribute('target')}'")[0]->getAttribute('name');
?>
                <div class="formSearchSelectorItem">
                    <input dojoType="dijit.form.RadioButton" id="<?php echo $this->domPrefix?>searchFields[<?php echo $i?>][<?php echo $k?>]" name="searchFields<?php echo $i?>" <?php if ($k == 0) echo 'checked="checked"' ?> value="<?php echo $element->getAttribute('target') ?>" type="radio" />
                    <label for="<?php echo $element->getAttribute('target') ?>"><?php echo $eName ?></label>
                </div>
<?php 
            $k++;
            endforeach;
?>
            </div>
<?php 
        endif;
?>
        </div>
<?php 
    endforeach;
?>
    </div>
    <div class="formSearchSubmit">
        <button type="submit" class="submit" dojoType="dijit.form.Button" iconClass="dijitIconSearch" id="<?=$this->domPrefix?>btnBuscar">Buscar</button>
    </div>

    <script type="dojo/method" event="onSubmit">
        if (this.validate()) {
            console.debug(this);
            dojo.forEach(this.elements, function(entry, i){
                console.debug(entry);
                console.debug(i);
            })
            //cargarDatos('<?php echo $this->model ?>', true, false, false, false, 'json', false, '<?php echo $this->domPrefix?>', false);
            return false;
        } else {
            alert('Por favor corrija los campos marcados.');
            return false;
        }
        return true;
    </script>
</div>
<?php 
}
?>
