<div dojoType="dijit.layout.TabContainer" style="width: 100%; height: 100%;" tabStrip="true" class="mainContent">
<?php
$i = 0;
foreach ($this->groups as $group) :
    $selected = ($i == 0) ? ' selected="true"' : '';
?>
<div dojoType="dijit.layout.ContentPane" title="<?php echo $group['group']?>" <?php echo $selected?>>
    <div dojoType="dijit.form.Form" id="<?php echo $this->domPrefix . $i?>_form" jsId="<?php echo $this->domPrefix . $i?>_form"  class="formSearch" encType="multipart/form-data" target="ifrm_process" action="<?php echo BASE_URL.'crud-request/multi-update' ?>" method="post">
        <div class="formSettingsInputs">
<?php 
    $subgroups = $this->model->getSubGroups($group['group']);
    foreach ($subgroups as $sg) :
        $sg['domId'] = $this->domPrefix.'_edit_';
        $sg['i'] = $i;
        if (!empty($sg['xml_children'])) {
            $xmlChildren = new Zwei_Admin_Xml(html_entity_decode($sg['xml_children']));
            Debug::write($xmlChildren);
        }
?>
            <div class="formSettingsItemContainer">
                <div class="item">
                    <label class="formSearchItemLabel"><?php echo $sg['id'] ?></label>
<?php 
        //if (!empty($sg['function'])&&class_exists($sg['function'])) {$f = new $sg['function'];$f->setId($i);}
        $sg['target'] = "data['{$sg['id']}']";
?>
                    <?php echo $this->action('index', $sg['type'], 'elements', $sg);?>
                    <div class="tip"><?php echo nl2br($sg['description'])?></div>
                </div>
            </div>
<?php 
        $i++;
    endforeach;
?>
        </div>
        <script type="dojo/method" event="onSubmit">
        if (this.validate()) {
            var form = new zwei.Form({dijitForm:this, iframe: dojo.byId('ifrm_process')});
            form.save();
            return false;
        } else {
            alert('Por favor favor corrija los campos marcados');
            return false;
        }
        </script>
        <button type="submit" dojoType="dijit.form.Button" iconClass="dijitIconSave" id="<?php echo $this->domPrefix ?>btnSaveSettings<?php echo $i?>">Guardar</button>
        <input type="hidden" name="model" value="<?php echo get_class($this->model) ?>" />
        <input type="hidden" name="nocache" value="<?php echo uniqid('nocache') ?>" />
    </div>
</div>
<?php 
endforeach;
?>
</div>