<div data-dojo-type="dijit/layout/TabContainer" style="width: 100%; height: 100%;" tabStrip="true" class="mainContent">
<?php
$i = 0;
foreach ($this->groups as $group) :
    $selected = ($i == 0) ? ' selected="true"' : '';
?>
<div data-dojo-type="dijit/layout/ContentPane" title="<?=$group['group']?>" <?=$selected?>>
    <div data-dojo-type="dijit/form/Form" id="<?=$this->domPrefix . $i?>_form" jsId="<?=$this->domPrefix . $i?>_form"  class="formSearch" encType="multipart/form-data" target="ifrm_process" action="<?=BASE_URL.'crud-request/multi-update' ?>" method="post">
        <div class="formSettingsInputs">
<?php 
    $subgroups = $this->model->getSubGroups($group['group']);
    foreach ($subgroups as $params) :
        $params['domId'] = $this->domPrefix.'_edit_';
        $params['i'] = $i;
?>
            <div class="formSettingsItemContainer" title="<?=nl2br($params['description'])?>">
                <div class="item">
                    <label class="formSearchItemLabel"><?=$params['id'] ?></label>
<?php 
        //if (!empty($sg['function'])&&class_exists($sg['function'])) {$f = new $sg['function'];$f->setId($i);}
        $params['target'] = "data['{$params['id']}']";
?>
                    <?=$this->action('index', $params['type'], 'elements', $params);?>
                </div>
            </div>
<?php 
        $i++;
    endforeach;
?>
        </div>
        <script type="dojo/method" event="onSubmit">
        if (this.validate()) {
            var form = new zwei.Form({dijitForm:this, iframe: dojo.byId('ifrm_process')});
            form.save();
            var observer = form.watch("response", function(name, oldValue, response) {
                if (response != null) {
                    dijit.byId('mainTabModule' + globalModuleId).refresh();
                    admportal.loadLayoutSettings();
                }
            });
            return false;
        } else {
            utils.showMessage('Por favor favor corrija los campos marcados', 'error');
            return false;
        }
        </script>
        <button type="submit" data-dojo-type="dijit/form/Button" iconClass="dijitIconSave" id="<?=$this->domPrefix ?>btnSaveSettings<?=$i?>">Guardar</button>
        <input type="hidden" name="model" value="<?=get_class($this->model) ?>" />
        <input type="hidden" name="nocache" value="<?=uniqid('nocache') ?>" />
    </div>
</div>
<?php 
endforeach;
?>
</div>