<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="es" />
    <script type="text/javascript">
    var base_url="<?=BASE_URL?>";
    var layout=<?=$this->layout?>; 
    </script>
    <style type="text/css">
    html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        overflow: hidden;
    }
    </style>
    <?=$this->headStyle()?>
    <?=$this->dojo()?>
    <?=$this->list?>
    <script type="text/javascript" src="<?=$this->base_url?>js/dojo.admin.js?v=7"></script>
    <script type="text/javascript">
    var utils=new zwei.Utils();
    var admportal=new zwei.Admportal();
    // Create a Standby instance
    dojo.addOnLoad(function() {
        var appStandBy = new dojox.widget.Standby({
            target: "borderContainer",
            imageText: "Loading ..."
        });
        document.body.appendChild(appStandBy.domNode);
        appStandBy.startup();
    	initLoad(<?=$this->layout?>);
        // Add pre-loading
    });

    function preLoading(){
        setTimeout(function() {
            dojo.fadeOut({
                node: "appLoader",
                duration: 500,
                onEnd: function() {
                    dojo.style("appLoader", "display", "none");
                }
            }).play();
        }, 500);
    }   
    </script>
</head>
<body class="<?=$this->bodyClass?>" onload="preLoading();">
    <<!--[if lt IE 7]>
    <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
    <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-cornerx.jpg' style='border: none;' alt='Cierra este aviso'/></a></div>
    <div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
      <div style='width: 75px; float: left;'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-warning.jpg' alt='¡Aviso!'/></div>
      <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
        <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>Usted está usando un navegador obsoleto.</div>
        <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>Para navegar mejor por este sitio, por favor, actualice su navegador.</div>
      </div>
      <div style='width: 75px; float: left;'><a href='http://www.mozilla-europe.org/es/firefox/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
      <div style='width: 75px; float: left;'><a href='http://www.microsoft.com/downloads/details.aspx?FamilyID=341c2ad5-8c3d-4347-8c03-08cdecd8852b&DisplayLang=es' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-ie8.jpg' style='border: none;' alt='Get Internet Explorer 8'/></a></div>
      <div style='width: 73px; float: left;'><a href='http://www.apple.com/es/safari/download/' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
      <div style='float: left;'><a href='http://www.google.com/chrome?hl=es' target='_blank'><img src='http://www.ie6nomore.com/files/theme/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
    </div>
    </div>
    <![endif]-->
    <!-- Loader -->
    <div id="appLoader" class="appLoader">
        <div>Cargando ...</div>
    </div>
    <!-- /Loader -->
    <div dojoType="dijit.layout.BorderContainer" id="borderContainer" jsId="borderContainer" data-dojo-props="design: 'headline', region: 'center', gutters: true" >
       <div dojoType="dojox.layout.ContentPane" jsId="contentPaneTop" data-dojo-props="splitter: true, region: 'top', executeScripts: true, scriptHasHooks: true" style="height: 60px;">
            <div id="logosAdm"></div>
            <div id="tituloAdm"></div>
            <div style="text-align: right; float: right;">
                <button data-dojo-type="dijit.form.DropDownButton" iconClass="dijitIconConfigure"><span>Configuracion</span>
                    <div data-dojo-type="dijit.Menu" id="confMenu" style="display: none;">
                        <div data-dojo-type="dijit.MenuItem" id="btnConfPersonal"
                            iconClass="dijitIconTask"
                            onclick="<?=$this->jsLoadModuleFunction?>('admin/components?p=personal-info.xml', '<?=uniqid() ?>', 'Datos Personales')">
                        Personal</div>
                   </div>
                </button>
                <button type="button" data-dojo-type="dijit.form.Button" name="btnSalir" id="btnSalir" iconClass="dijitIconFilter">Salir</button>
            </div>
            <div id="infoUsr" style="text-align: right; float: right; padding-right: 20px; padding-top:6px; font-weight: bold">Bienvenido
            <?=$this->user_name?>
            </div>
        </div>
        <!-- Panel derecho -->
        <div data-dojo-type="dojox.layout.ExpandoPane" id="menuExpand" jsId="menuExpand" data-dojo-props="region: 'left', splitter: true, previewOnDblClick: false, startExpanded: true, maxWidth: 250, title: 'Men&uacute; Principal', style: 'width: 250px;'">
           <div id="appToolboxContainer" style="padding-top:4px;">
                <div id="arbolPrincipal" style="padding-top:4px;"></div>
           </div>
        </div>
        <!-- Panel central -->
        <div id="mainPane" jsId="mainPane" dojoType="dojox.layout.ContentPane" splitter="true" region="center" executeScripts="true" scriptHasHooks="true">
            <div dojoType="dijit.layout.TabContainer" id="tabContainer" data-dojo-props="executeScripts: true, scriptHasHooks: true" jsId="tabContainer" style="width:100%;height:100%;top:0px;" tabPosition="top"></div>
        </div>
        <div data-dojo-type="dojox.layout.ContentPane" jsId="contentPaneBottom" data-dojo-props='region:"bottom"'>
            <span style="float:right;margin-right: 6px">
                <span style="float: left; padding-right: 10px;" id="zweicomLegend">&nbsp;</span> <img id="zweicomLogo" src="" />  
            </span>
        </div>
    </div>
    <div data-dojo-type="dojox/widget/Toaster" jsId="firstToaster" data-dojo-props="positionDirection:'br-left'" id="firstToaster"></div>
    <iframe name="ifrm_process" id="ifrm_process" style="display: none;"  src="" ></iframe>
</body>
</html>
