<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="es" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
    <script type="text/javascript">
    var base_url="<?php echo BASE_URL; ?>";
    var layout=<?php echo $this->layout;?>; 
    </script>
    <style type="text/css">
    html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        overflow: hidden;
    }
    </style>
    <?php echo $this->headStyle()?>
    <?php echo $this->dojo()?>
    <?php echo $this->list?>
    <script type="text/javascript" src="<?=$this->base_url?>js/dojo.admin.js?v=7"></script>
    <script type="text/javascript" src="<?=$this->base_url?>js/ajax.js"></script>
    <script type="text/javascript" src="<?=$this->base_url?>js/admin.js?v=6"></script>
    <script type="text/javascript" src="<?=$this->base_url?>js/md5.js"></script>
    <script type="text/javascript">
    // Create a Standby instance
    dojo.addOnLoad(function() {
        var appStandBy = new dojox.widget.Standby({
            target: "borderContainer",
            imageText: "Loading ..."
        });
        document.body.appendChild(appStandBy.domNode);
        appStandBy.startup();
    	initLoad(<?php echo $this->layout?>);
        // Add pre-loading
    });

    function preLoading(){
        setTimeout(function() {
            dojo.fadeOut({
                node: "appLoader",
                duration: 500,
                onEnd: function() {
                    dojo.style("appLoader", "display", "none");
                }
            }).play();
        }, 500);
    }   
    </script>
</head>
<body class="<?php echo $this->bodyClass?>" onload="preLoading();">
    <!--[if lt IE 7]> <div style=' clear: both; height: 59px; padding:0 0 0 15px; position: relative;'> <a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0012_spanish_LATAM.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div> <![endif]-->
        <!-- Loader -->
    <div id="appLoader" class="appLoader">
        <div>Cargando ...</div>
    </div>
    <!-- /Loader -->
    <div dojoType="dijit.layout.BorderContainer" id="borderContainer" jsId="borderContainer" data-dojo-props="design: 'headline', region: 'center', gutters: true" >
       <div dojoType="dojox.layout.ContentPane" jsId="contentPaneTop" data-dojo-props="splitter: true, region: 'top', executeScripts: true, scriptHasHooks: true" style="height: 60px;">
            <div id="logosAdm"></div>
            <div id="tituloAdm"></div>
            <div style="text-align: right; float: right;">
                <button data-dojo-type="dijit.form.DropDownButton" iconClass="dijitIconConfigure"><span>Configuracion</span>
                    <div data-dojo-type="dijit.Menu" id="confMenu" style="display: none;">
                        <div data-dojo-type="dijit.MenuItem" id="btnConfPersonal"
                            iconClass="dijitIconTask"
                            onclick="<?=$this->jsLoadModuleFunction?>('admin/components?p=personal-info.xml', '<?= uniqid() ?>', 'Datos Personales')">
                        Personal</div>
                   </div>
                </button>
                <button type="button" data-dojo-type="dijit.form.Button" name="btnSalir" id="btnSalir" iconClass="dijitIconFilter">Salir</button>
            </div>
            <div id="infoUsr" style="text-align: right; float: right; padding-right: 20px; padding-top:6px; font-weight: bold">Bienvenido
			<?php echo $this->user_name?>
            </div>
        </div>
        <!-- Panel derecho -->
        <div data-dojo-type="dojox.layout.ExpandoPane" id="menuExpand" jsId="menuExpand" data-dojo-props="region: 'left', splitter: true, previewOnDblClick: false, startExpanded: true, maxWidth: 250, title: 'Men&uacute; Principal', style: 'width: 250px;'">
           <div id="appToolboxContainer" style="padding-top:4px;">
                <div id="arbolPrincipal" style="padding-top:4px;"></div>
           </div>
        </div>
        <!-- Panel central -->
        <div id="panel_central" id="panelCentral" jsId="dojo_panel_central" dojoType="dojox.layout.ContentPane" splitter="true" region="center" executeScripts="true" scriptHasHooks="true">
            <div dojoType="dijit.layout.TabContainer" id="tabContainer" data-dojo-props="executeScripts: true, scriptHasHooks: true" jsId="tabContainer" style="width:100%;height:100%;top:0px;" tabPosition="top"></div>
        </div>
        <div data-dojo-type="dojox.layout.ContentPane" jsId="contentPaneBottom" data-dojo-props='region:"bottom", style:"background-color: #b39b86; height: auto;"'>
            <span style="float:right;margin-right: 6px">
                <span style="float: left">&nbsp; &copy; Zweicom 2012 &nbsp; </span> <img src="<?php echo BASE_URL?>/images/logo_zweicom26x15.png" />  
            </span>
        </div>
    </div>
    <div data-dojo-type="dojox/widget/Toaster" jsId="firstToaster" data-dojo-props="positionDirection:'br-left'" id="firstToaster"></div>
    <iframe name="ifrm_process" id="ifrm_process" style="display: none;"  src="" ></iframe>
</body>
</html>
