<!DOCTYPE html>
<html>
<head>
    <!--------------------
    LOGIN FORM
    by: Amit Jakhu
    www.amitjakhu.com
    --------------------->
    <!--META-->
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?=$this->adminTitle?></title>
    <link href="<?=BASE_URL?>favicon.ico" rel="shortcut icon"/>
    <?=$this->headStyle()?>
    <?=$this->dojo()?>
    <link href="<?=BASE_URL ?>css/login.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
    require(["dojo/ready", "dojo/parser", "dijit/registry", "dijit/Dialog"], function(ready, parser, registry){
        ready(function(){
            dojo.connect(dijit.byId('username'), 'onFocus', function() {
                dojo.byId("user_icon").style.left="-48px";
            });
            
            dojo.connect(dijit.byId('username'), 'onBlur', function() {
                dojo.byId("user_icon").style.left="0px";
            });

            dojo.connect(dijit.byId('password'), 'onFocus', function() {
                dojo.byId("pass_icon").style.left="-48px";
            });
            
            dojo.connect(dijit.byId('password'), 'onBlur', function() {
                dojo.byId("pass_icon").style.left="0px";
            });
            
        });
    });
    </script>
</head>
<body class="<?=$this->bodyClass?> login">
<?php
if ($this->isObsoleteBrowser) :
?>
    <div style='border: 1px solid #F7941D; background: #FEEFDA; text-align: center; clear: both; height: 75px; position: relative;'>
    <div style='position: absolute; right: 3px; top: 3px; font-family: courier new; font-weight: bold;'><a href='#' onclick='javascript:this.parentNode.parentNode.style.display="none"; return false;'><img src='<?=BASE_URL?>/images/ie6nomore-cornerx.jpg' style='border: none;' alt='Cierra este aviso'/></a></div>
    <div style='width: 640px; margin: 0 auto; text-align: left; padding: 0; overflow: hidden; color: black;'>
      <div style='width: 75px; float: left;'><img src='<?=BASE_URL?>/images/ie6nomore-warning.jpg' alt='¡Aviso!'/></div>
      <div style='width: 275px; float: left; font-family: Arial, sans-serif;'>
        <div style='font-size: 14px; font-weight: bold; margin-top: 12px;'>Usted está usando un navegador obsoleto.</div>
        <div style='font-size: 12px; margin-top: 6px; line-height: 12px;'>Para navegar mejor por este sitio, por favor, actualice su navegador.</div>
      </div>
      <div style='width: 75px; float: left;'><a href='http://www.mozilla-europe.org/es/firefox/' target='_blank'><img src='<?=BASE_URL?>/images/ie6nomore-firefox.jpg' style='border: none;' alt='Get Firefox 3.5'/></a></div>
      <div style='width: 75px; float: left;'><a href='http://www.microsoft.com/es-es/download/internet-explorer.aspx' target='_blank'><img src='<?=BASE_URL?>/images/ie6nomore-ie<?=$this->ieMinVersion?>.jpg' style='border: none;' alt='Get Internet Explorer 9'/></a></div>
      <div style='width: 73px; float: left;'><a href='http://www.apple.com/es/safari/download/' target='_blank'><img src='<?=BASE_URL?>/images/ie6nomore-safari.jpg' style='border: none;' alt='Get Safari 4'/></a></div>
      <div style='float: left;'><a href='http://www.google.com/chrome?hl=es' target='_blank'><img src='<?=BASE_URL?>/images/ie6nomore-chrome.jpg' style='border: none;' alt='Get Google Chrome'/></a></div>
    </div>
    </div>
<?php
endif;
?>
    <div id="wrapper">
        <div class="user-icon" id="user_icon"></div>
        <div class="pass-icon" id="pass_icon"></div>
        <div class="operLogo" style="background-image: url(<?=BASE_URL ?>upfiles/corporative/<?=$this->urlLogoOper?>);"></div>
        <div class="login-form">
            <div class="header">
                <h1><?=$this->adminTitle?></h1>
                <span></span>
            </div>
                <?php if ($this->errorMessage != "") : ?><p class="error"><?=$this->errorMessage;?></p><?php endif; ?>
                <?=$this->loginForm?>
        </div>
    </div>
    <div class="gradient"></div>
    <div class="gamelenaLogo"></div>
</body>
</html>
