#!/bin/bash
ZWC_ADMPORTAL_PATH=$ZWC_ADMPORTAL
DEST_PATH=$PWD


VAR=$PWD


if [ -d /etc/httpd/ ]; then 
		echo "httpd"
		cd /etc/httpd/
		sudo mkdir -p alias
		sudo chmod -R 777 alias
		cd alias
		sudo echo "Alias /${VAR##*/} \"$DEST_PATH/web/public/\"
		 <Directory \"$DEST_PATH/web/public/\">
	    Options Indexes MultiViews FollowSymLinks
	    AllowOverride All
	    allow from all
	    SetEnv APPLICATION_ENV development
		 </Directory>" > ${VAR##*/}.conf

else
		echo "apache2"
		cd /etc/apache2/
		sudo mkdir -p alias
		sudo chmod -R 777 alias
		cd alias
		sudo echo "Alias /${VAR##*/} \"$DEST_PATH/web/public/\"
		 <Directory \"$DEST_PATH/web/public/\">
	    Options Indexes MultiViews FollowSymLinks
	    AllowOverride All
	    allow from all
	    SetEnv APPLICATION_ENV development
		 </Directory>" > ${VAR##*/}.conf


fi
