<script type="text/javascript" src="/libs/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
    tinyMCE.init({
        // General options
<?php
if ($this->tinyMceInit) :
    echo $this->tinyMceInit;
elseif ($this->tinyMceTemplate == 'simple') :
?>
        mode : "exact",
        theme: "simple",
        elements : "<?php echo $this->target?>",
        theme : "simple",
        auto_focus: "<?php echo $this->domId . $this->i?>",
        setup : function(ed) {
            ed.onClick.add(function(ed, e) {
                this.focus();
            });
        }
<?
elseif ($this->tinyMceTemplate == 'advanced') :
?>
        mode : "exact",
        theme: "advanced",
        elements : "<?php echo $this->target?>",
        theme : "advanced",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,
        setup : function(ed) {
            ed.onClick.add(function(ed, e) {
                this.focus();
            });
        }
<?
elseif ($this->tinyMceTemplate == 'fullAdvanced') :
?>
        // Theme options
        mode : "exact",
        theme: "advanced",
        elements : "<?php echo $this->target?>",
        plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Example content CSS (should be your site CSS)
        // using false to ensure that the default browser settings are used for best Accessibility
        // ACCESSIBILITY SETTINGS
        content_css : false,
        // Use browser preferred colors for dialogs.
        browser_preferred_colors : true,
        detect_highcontrast : true,

        // Drop lists for link/image/media/template dialogs
		template_external_list_url : "lists/template_list.js",
		external_link_list_url : "lists/link_list.js",
		external_image_list_url : "lists/image_list.js",
		media_external_list_url : "lists/media_list.js",

        // Style formats
        style_formats : [
            {title : 'Bold text', inline : 'b'},
            {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
            {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
            {title : 'Example 1', inline : 'span', classes : 'example1'},
            {title : 'Example 2', inline : 'span', classes : 'example2'},
            {title : 'Table styles'},
            {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
        ],

        // Replace values for the template plugin
        template_replace_values : {
            username : "Some User",
            staffid : "991234"
        },

        setup : function(ed) {
            ed.onClick.add(function(ed, e) {
                this.focus();
            });
        }
<?php 
endif;
?>
    });
    
</script>
<div>
    <textarea id="<?php echo $this->domId . $this->i?>" name="<?php echo $this->target?>" rows="15" cols="80" style="width: 80%" class="mceEditor">
    <?php echo $this->value ?>
    </textarea>
</div>        

